### ISSUE TITLE
Is it possible to build non-statically?

### ISSUE THREAD

**Issue by RPGillespie6** [hduong85/arm_adb#6]
This project works great, but currently builds a large (relatively) statically linked binary. We already have libcrypto and libssl in our board, is there a built-in way to build with dynamic linking instead?

**Comment by qhuyduong** [comment]
Hi,

Yes it is possible to build this adb project with dynamic linking. You just need to remove "-static" in src/Makefile.am, re-configure and build.

However please note that adb originally uses boringssl (developed by google) instead of openssl. That's why in the guideline, before compiling adb, you need to compile my modified "openssl" library first (https://github.com/hduong85/openssl-1.0.2l). This is the openssl + some required functions ported from boringssl. So in order to build adb with dynamic linking, you need to make sure your libssl has the required functions (you can see the commit log).
Or in a more simple way, you can just need to follow my guideline to build openssl, then copy the output folders (/tmp/openssl/include and /tmp/openssl/lib) to another place (/usr/lib/... for example), remove "-static", re-configure and build.

Have fun!

**Comment by RPGillespie6** [comment]
Thanks, I got it working by creating a static archive containing just the boringssl functions and then dynamically linking against our own libcrypto. Worked like a charm!
